"""empty message

Revision ID: 7fb08af99769
Revises: 33335c6ece32
Create Date: 2023-05-06 16:27:01.933172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fb08af99769'
down_revision = '33335c6ece32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.drop_column('user', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission', mysql.VARCHAR(length=50), nullable=True))
    op.create_table('admin',
    sa.Column('aid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('avater', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('permission', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('aid', 'number'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
