"""empty message

Revision ID: 33335c6ece32
Revises: 0bc974f9be4a
Create Date: 2023-05-04 21:08:09.182863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33335c6ece32'
down_revision = '0bc974f9be4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.drop_column('user', 'avater')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avater', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
